import { useState } from "react";
import {
  Box,
  Heading,
  Text,
  HStack,
  VStack,
  Input,
  Button,
  Badge,
  Wrap,
  WrapItem,
  Tag,
  TagLabel,
  TagCloseButton,
  SimpleGrid,
  Skeleton,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from "@chakra-ui/react";
import { Plus, Eye } from "lucide-react";
import { useDarkWebKeywords, useDarkWebMatches, useAddDarkWebKeyword, useDeleteDarkWebKeyword } from "../api/hooks";

const RISK_COLORS: Record<string, string> = { critical: "red", high: "orange", medium: "yellow", low: "gray" };

export function DarkWebMonitoringPage() {
  const keywords = useDarkWebKeywords();
  const matches = useDarkWebMatches();
  const addKeyword = useAddDarkWebKeyword();
  const deleteKeyword = useDeleteDarkWebKeyword();
  const [input, setInput] = useState("");

  const handleAdd = () => {
    if (!input.trim()) return;
    addKeyword.mutate(input.trim(), { onSuccess: () => setInput("") });
  };

  return (
    <Box>
      <Heading size="lg" mb={1}>Dark Web Monitoring</Heading>
      <Text color="text.muted" fontSize="sm" mb={4}>
        Track organization keywords (company name, domains, executive emails) for mentions in breach-notification
        feeds and paste-site indexes.
      </Text>

      <Alert status="warning" mb={6} fontSize="sm">
        <AlertIcon />
        <Box>
          <AlertTitle>No real breach-feed source is configured yet</AlertTitle>
          <AlertDescription>
            Results below are generated by a deterministic sample-data source so you can preview the UI. Every
            result is badged <Badge fontSize="9px" ml={1}>Sample Data</Badge>. A real feed can be wired in later via
            the pluggable data-source interface without any UI changes.
          </AlertDescription>
        </Box>
      </Alert>

      <Box borderWidth="1px" borderColor="border.default" bg="bg.surface" borderRadius="xl" p={5} mb={6}>
        <Text fontSize="sm" fontWeight="medium" mb={3}>Tracked Keywords</Text>
        <HStack mb={3}>
          <Input
            placeholder="e.g. 1cloudng.com, exec@1cloudng.com"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleAdd()}
          />
          <Button leftIcon={<Plus size={16} />} colorScheme="orange" onClick={handleAdd} isLoading={addKeyword.isPending}>Add</Button>
        </HStack>
        {keywords.isLoading ? (
          <Skeleton h="32px" />
        ) : keywords.data && keywords.data.data.length > 0 ? (
          <Wrap spacing={2}>
            {keywords.data.data.map((k) => (
              <WrapItem key={k.id}>
                <Tag size="lg" variant="solid" colorScheme="orange" borderRadius="full">
                  <TagLabel>{k.keyword}</TagLabel>
                  <TagCloseButton onClick={() => deleteKeyword.mutate(k.id)} />
                </Tag>
              </WrapItem>
            ))}
          </Wrap>
        ) : (
          <Text fontSize="sm" color="text.muted">No keywords tracked yet.</Text>
        )}
      </Box>

      <Heading size="md" mb={3}>Matches</Heading>
      {matches.isLoading ? (
        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={4}>
          {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} h="120px" borderRadius="xl" />)}
        </SimpleGrid>
      ) : !matches.data || matches.data.data.length === 0 ? (
        <Box p={12} textAlign="center" borderWidth="1px" borderColor="border.default" borderRadius="xl" bg="bg.surface">
          <Eye size={32} color="#64748b" style={{ margin: "0 auto 12px" }} />
          <Text color="text.muted">
            {keywords.data && keywords.data.data.length > 0 ? "No matches found for tracked keywords." : "Add a keyword above to start monitoring."}
          </Text>
        </Box>
      ) : (
        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={4}>
          {matches.data.data.map((match, i) => (
            <Box key={i} borderWidth="1px" borderColor="border.default" bg="bg.surface" borderRadius="xl" p={4}>
              <HStack justify="space-between" mb={2}>
                <Text fontSize="xs" fontFamily="mono" color="text.muted">{match.source}</Text>
                <HStack spacing={1}>
                  {match.isSample && <Badge fontSize="9px" colorScheme="purple">Sample Data</Badge>}
                  <Badge colorScheme={RISK_COLORS[match.riskLevel]} fontSize="9px">{match.riskLevel}</Badge>
                </HStack>
              </HStack>
              <Text fontSize="sm" mb={2}>{match.snippet}</Text>
              <HStack justify="space-between" fontSize="xs" color="text.muted">
                <Text>Keyword: <Text as="span" fontFamily="mono">{match.matchedKeyword}</Text></Text>
                <Text>{new Date(match.dateFound).toLocaleDateString()}</Text>
              </HStack>
            </Box>
          ))}
        </SimpleGrid>
      )}
    </Box>
  );
}
