CREATE TABLE IF NOT EXISTS "ransomware_iocs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ransomware_iocs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_name" text NOT NULL,
	"ioc_type" text NOT NULL,
	"ioc_value" text NOT NULL,
	"synced_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ransomware_iocs_group_name_ioc_type_ioc_value_unique" UNIQUE("group_name","ioc_type","ioc_value")
);
--> statement-breakpoint
ALTER TABLE "ransomware_groups" ADD COLUMN "attack_techniques" jsonb;--> statement-breakpoint
ALTER TABLE "ransomware_groups" ADD COLUMN "attack_synced_at" timestamp;