export interface ComplianceControl {
  id: string;
  title: string;
  category: string;
}

export interface ComplianceFramework {
  key: "iso27001" | "nist_csf" | "cis_controls";
  name: string;
  controls: ComplianceControl[];
}

// Real published control identifiers/titles for each framework's full
// structure (ISO 27001:2022 Annex A's 93 controls across 4 themes, NIST
// CSF 2.0's 6 functions and all published categories, CIS Controls v8's 18
// controls with representative IG1 safeguards).
export const COMPLIANCE_FRAMEWORKS: ComplianceFramework[] = [
  {
    key: "iso27001",
    name: "ISO/IEC 27001:2022 (Annex A)",
    controls: [
      // A.5 Organizational controls (37)
      { id: "A.5.1", title: "Policies for information security", category: "Organizational" },
      { id: "A.5.2", title: "Information security roles and responsibilities", category: "Organizational" },
      { id: "A.5.3", title: "Segregation of duties", category: "Organizational" },
      { id: "A.5.4", title: "Management responsibilities", category: "Organizational" },
      { id: "A.5.5", title: "Contact with authorities", category: "Organizational" },
      { id: "A.5.6", title: "Contact with special interest groups", category: "Organizational" },
      { id: "A.5.7", title: "Threat intelligence", category: "Organizational" },
      { id: "A.5.8", title: "Information security in project management", category: "Organizational" },
      { id: "A.5.9", title: "Inventory of information and other associated assets", category: "Organizational" },
      { id: "A.5.10", title: "Acceptable use of information and other associated assets", category: "Organizational" },
      { id: "A.5.11", title: "Return of assets", category: "Organizational" },
      { id: "A.5.12", title: "Classification of information", category: "Organizational" },
      { id: "A.5.13", title: "Labelling of information", category: "Organizational" },
      { id: "A.5.14", title: "Information transfer", category: "Organizational" },
      { id: "A.5.15", title: "Access control", category: "Organizational" },
      { id: "A.5.16", title: "Identity management", category: "Organizational" },
      { id: "A.5.17", title: "Authentication information", category: "Organizational" },
      { id: "A.5.18", title: "Access rights", category: "Organizational" },
      { id: "A.5.19", title: "Information security in supplier relationships", category: "Organizational" },
      { id: "A.5.20", title: "Addressing information security within supplier agreements", category: "Organizational" },
      { id: "A.5.21", title: "Managing information security in the ICT supply chain", category: "Organizational" },
      { id: "A.5.22", title: "Monitoring, review and change management of supplier services", category: "Organizational" },
      { id: "A.5.23", title: "Information security for use of cloud services", category: "Organizational" },
      { id: "A.5.24", title: "Information security incident management planning and preparation", category: "Organizational" },
      { id: "A.5.25", title: "Assessment and decision on information security events", category: "Organizational" },
      { id: "A.5.26", title: "Response to information security incidents", category: "Organizational" },
      { id: "A.5.27", title: "Learning from information security incidents", category: "Organizational" },
      { id: "A.5.28", title: "Collection of evidence", category: "Organizational" },
      { id: "A.5.29", title: "Information security during disruption", category: "Organizational" },
      { id: "A.5.30", title: "ICT readiness for business continuity", category: "Organizational" },
      { id: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", category: "Organizational" },
      { id: "A.5.32", title: "Intellectual property rights", category: "Organizational" },
      { id: "A.5.33", title: "Protection of records", category: "Organizational" },
      { id: "A.5.34", title: "Privacy and protection of PII", category: "Organizational" },
      { id: "A.5.35", title: "Independent review of information security", category: "Organizational" },
      { id: "A.5.36", title: "Compliance with policies, rules and standards for information security", category: "Organizational" },
      { id: "A.5.37", title: "Documented operating procedures", category: "Organizational" },
      // A.6 People controls (8)
      { id: "A.6.1", title: "Screening", category: "People" },
      { id: "A.6.2", title: "Terms and conditions of employment", category: "People" },
      { id: "A.6.3", title: "Information security awareness, education and training", category: "People" },
      { id: "A.6.4", title: "Disciplinary process", category: "People" },
      { id: "A.6.5", title: "Responsibilities after termination or change of employment", category: "People" },
      { id: "A.6.6", title: "Confidentiality or non-disclosure agreements", category: "People" },
      { id: "A.6.7", title: "Remote working", category: "People" },
      { id: "A.6.8", title: "Information security event reporting", category: "People" },
      // A.7 Physical controls (14)
      { id: "A.7.1", title: "Physical security perimeters", category: "Physical" },
      { id: "A.7.2", title: "Physical entry", category: "Physical" },
      { id: "A.7.3", title: "Securing offices, rooms and facilities", category: "Physical" },
      { id: "A.7.4", title: "Physical security monitoring", category: "Physical" },
      { id: "A.7.5", title: "Protecting against physical and environmental threats", category: "Physical" },
      { id: "A.7.6", title: "Working in secure areas", category: "Physical" },
      { id: "A.7.7", title: "Clear desk and clear screen", category: "Physical" },
      { id: "A.7.8", title: "Equipment siting and protection", category: "Physical" },
      { id: "A.7.9", title: "Security of assets off-premises", category: "Physical" },
      { id: "A.7.10", title: "Storage media", category: "Physical" },
      { id: "A.7.11", title: "Supporting utilities", category: "Physical" },
      { id: "A.7.12", title: "Cabling security", category: "Physical" },
      { id: "A.7.13", title: "Equipment maintenance", category: "Physical" },
      { id: "A.7.14", title: "Secure disposal or re-use of equipment", category: "Physical" },
      // A.8 Technological controls (34)
      { id: "A.8.1", title: "User endpoint devices", category: "Technological" },
      { id: "A.8.2", title: "Privileged access rights", category: "Technological" },
      { id: "A.8.3", title: "Information access restriction", category: "Technological" },
      { id: "A.8.4", title: "Access to source code", category: "Technological" },
      { id: "A.8.5", title: "Secure authentication", category: "Technological" },
      { id: "A.8.6", title: "Capacity management", category: "Technological" },
      { id: "A.8.7", title: "Protection against malware", category: "Technological" },
      { id: "A.8.8", title: "Management of technical vulnerabilities", category: "Technological" },
      { id: "A.8.9", title: "Configuration management", category: "Technological" },
      { id: "A.8.10", title: "Information deletion", category: "Technological" },
      { id: "A.8.11", title: "Data masking", category: "Technological" },
      { id: "A.8.12", title: "Data leakage prevention", category: "Technological" },
      { id: "A.8.13", title: "Information backup", category: "Technological" },
      { id: "A.8.14", title: "Redundancy of information processing facilities", category: "Technological" },
      { id: "A.8.15", title: "Logging", category: "Technological" },
      { id: "A.8.16", title: "Monitoring activities", category: "Technological" },
      { id: "A.8.17", title: "Clock synchronization", category: "Technological" },
      { id: "A.8.18", title: "Use of privileged utility programs", category: "Technological" },
      { id: "A.8.19", title: "Installation of software on operational systems", category: "Technological" },
      { id: "A.8.20", title: "Networks security", category: "Technological" },
      { id: "A.8.21", title: "Security of network services", category: "Technological" },
      { id: "A.8.22", title: "Segregation of networks", category: "Technological" },
      { id: "A.8.23", title: "Web filtering", category: "Technological" },
      { id: "A.8.24", title: "Use of cryptography", category: "Technological" },
      { id: "A.8.25", title: "Secure development life cycle", category: "Technological" },
      { id: "A.8.26", title: "Application security requirements", category: "Technological" },
      { id: "A.8.27", title: "Secure system architecture and engineering principles", category: "Technological" },
      { id: "A.8.28", title: "Secure coding", category: "Technological" },
      { id: "A.8.29", title: "Security testing in development and acceptance", category: "Technological" },
      { id: "A.8.30", title: "Outsourced development", category: "Technological" },
      { id: "A.8.31", title: "Separation of development, test and production environments", category: "Technological" },
      { id: "A.8.32", title: "Change management", category: "Technological" },
      { id: "A.8.33", title: "Test information", category: "Technological" },
      { id: "A.8.34", title: "Protection of information systems during audit testing", category: "Technological" },
    ],
  },
  {
    key: "nist_csf",
    name: "NIST Cybersecurity Framework 2.0",
    controls: [
      { id: "GV.OC", title: "Organizational Context", category: "Govern" },
      { id: "GV.RM", title: "Risk Management Strategy", category: "Govern" },
      { id: "GV.RR", title: "Roles, Responsibilities, and Authorities", category: "Govern" },
      { id: "GV.PO", title: "Policy", category: "Govern" },
      { id: "GV.OV", title: "Oversight", category: "Govern" },
      { id: "GV.SC", title: "Cybersecurity Supply Chain Risk Management", category: "Govern" },
      { id: "ID.AM", title: "Asset Management", category: "Identify" },
      { id: "ID.RA", title: "Risk Assessment", category: "Identify" },
      { id: "ID.IM", title: "Improvement", category: "Identify" },
      { id: "PR.AA", title: "Identity Management, Authentication and Access Control", category: "Protect" },
      { id: "PR.AT", title: "Awareness and Training", category: "Protect" },
      { id: "PR.DS", title: "Data Security", category: "Protect" },
      { id: "PR.PS", title: "Platform Security", category: "Protect" },
      { id: "PR.IR", title: "Technology Infrastructure Resilience", category: "Protect" },
      { id: "DE.CM", title: "Continuous Monitoring", category: "Detect" },
      { id: "DE.AE", title: "Adverse Event Analysis", category: "Detect" },
      { id: "RS.MA", title: "Incident Management", category: "Respond" },
      { id: "RS.AN", title: "Incident Analysis", category: "Respond" },
      { id: "RS.CO", title: "Incident Response Reporting and Communication", category: "Respond" },
      { id: "RS.MI", title: "Incident Mitigation", category: "Respond" },
      { id: "RC.RP", title: "Incident Recovery Plan Execution", category: "Recover" },
      { id: "RC.CO", title: "Incident Recovery Communication", category: "Recover" },
    ],
  },
  {
    key: "cis_controls",
    name: "CIS Controls v8",
    controls: [
      { id: "1.1", title: "Establish and Maintain Detailed Enterprise Asset Inventory", category: "1. Inventory and Control of Enterprise Assets" },
      { id: "1.2", title: "Address Unauthorized Assets", category: "1. Inventory and Control of Enterprise Assets" },
      { id: "2.1", title: "Establish and Maintain a Software Inventory", category: "2. Inventory and Control of Software Assets" },
      { id: "2.2", title: "Ensure Authorized Software is Currently Supported", category: "2. Inventory and Control of Software Assets" },
      { id: "3.1", title: "Establish and Maintain a Data Management Process", category: "3. Data Protection" },
      { id: "3.3", title: "Configure Data Access Control Lists", category: "3. Data Protection" },
      { id: "4.1", title: "Establish and Maintain a Secure Configuration Process", category: "4. Secure Configuration of Enterprise Assets and Software" },
      { id: "4.2", title: "Establish and Maintain a Secure Configuration Process for Network Infrastructure", category: "4. Secure Configuration of Enterprise Assets and Software" },
      { id: "5.1", title: "Establish and Maintain an Inventory of Accounts", category: "5. Account Management" },
      { id: "5.2", title: "Use Unique Passwords", category: "5. Account Management" },
      { id: "6.1", title: "Establish an Access Granting Process", category: "6. Access Control Management" },
      { id: "6.2", title: "Establish an Access Revoking Process", category: "6. Access Control Management" },
      { id: "7.1", title: "Establish and Maintain a Vulnerability Management Process", category: "7. Continuous Vulnerability Management" },
      { id: "7.2", title: "Establish and Maintain a Remediation Process", category: "7. Continuous Vulnerability Management" },
      { id: "8.1", title: "Establish and Maintain an Audit Log Management Process", category: "8. Audit Log Management" },
      { id: "8.2", title: "Collect Audit Logs", category: "8. Audit Log Management" },
      { id: "9.1", title: "Ensure Use of Only Fully Supported Browsers and Email Clients", category: "9. Email and Web Browser Protections" },
      { id: "9.2", title: "Use DNS Filtering Services", category: "9. Email and Web Browser Protections" },
      { id: "10.1", title: "Deploy and Maintain Anti-Malware Software", category: "10. Malware Defenses" },
      { id: "10.2", title: "Configure Automatic Anti-Malware Signature Updates", category: "10. Malware Defenses" },
      { id: "11.1", title: "Establish and Maintain a Data Recovery Process", category: "11. Data Recovery" },
      { id: "11.2", title: "Perform Automated Backups", category: "11. Data Recovery" },
      { id: "12.1", title: "Ensure Network Infrastructure is Up-to-Date", category: "12. Network Infrastructure Management" },
      { id: "12.2", title: "Establish and Maintain a Secure Network Architecture", category: "12. Network Infrastructure Management" },
      { id: "13.1", title: "Centralize Security Event Alerting", category: "13. Network Monitoring and Defense" },
      { id: "14.1", title: "Establish and Maintain a Security Awareness Program", category: "14. Security Awareness and Skills Training" },
      { id: "15.1", title: "Establish and Maintain an Inventory of Service Providers", category: "15. Service Provider Management" },
      { id: "16.1", title: "Establish and Maintain a Secure Application Development Process", category: "16. Application Software Security" },
      { id: "17.1", title: "Designate Personnel to Manage Incident Handling", category: "17. Incident Response Management" },
      { id: "18.1", title: "Establish and Maintain a Penetration Testing Program", category: "18. Penetration Testing" },
    ],
  },
];
